# Generated by Django 4.2.20 on 2025-05-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to='qr-images/'),
        ),
    ]
